//! DKIM signing key management (admin): generate a key per domain and selector,
//! list the DNS records to publish, switch signing over to a new key, revoke.
//!
//! The private half is generated by `server::dkim`, encrypted at rest with the
//! module's `MailCrypto` (like account passwords), and used later by the
//! outbound worker. The public half is shown so the administrator can publish
//! the `<selector>._domainkey.<domain>` TXT record — without which no verifier
//! trusts our signature. The private half NEVER leaves this module: it is not
//! selected here, not serialised, not logged.
//!
//! ── Rotation ────────────────────────────────────────────────────────────────
//! A key cannot be replaced in place: DNS propagates over hours and receivers
//! cache records, so swapping the key under a fixed selector leaves a window
//! where signatures verify against a stale record and the mail lands in spam.
//! The supported sequence is therefore: create a key under a NEW selector (it
//! starts INACTIVE), publish its record, wait, activate it, then delete the
//! old one. Hence `selector` is an input, several keys may coexist per domain,
//! and exactly one of them is active — see migration 000023.

use axum::{
    extract::{Path, State},
    Json,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{
    errors::MailError, middleware::AuthUser, server::dkim, services::crypto::MailCrypto,
    state::AppState,
};

/// Selector used when the administrator does not name one. Rotating means
/// creating the next key under a different selector, e.g. a date.
const DEFAULT_SELECTOR: &str = "kubuno";

/// Longest DNS label (RFC 1035 §2.3.4).
const MAX_SELECTOR_LEN: usize = 63;

#[derive(sqlx::FromRow)]
pub struct DkimKeyRow {
    pub id:         Uuid,
    pub domain:     String,
    pub selector:   String,
    pub algorithm:  String,
    pub public_key: String,
    pub is_active:  bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize)]
pub struct DkimKeyView {
    pub id:         Uuid,
    pub domain:     String,
    pub selector:   String,
    pub algorithm:  String,
    /// Whether this is the key outgoing mail is signed with, for this domain.
    pub is_active:  bool,
    pub created_at: DateTime<Utc>,
    /// The exact DNS record to publish: name and value.
    pub dns_name:   String,
    pub dns_value:  String,
}

impl DkimKeyView {
    fn from_row(r: DkimKeyRow) -> Self {
        let k = if r.algorithm.starts_with("ed25519") { "ed25519" } else { "rsa" };
        DkimKeyView {
            dns_name:  format!("{}._domainkey.{}", r.selector, r.domain),
            dns_value: format!("v=DKIM1; k={k}; p={}", r.public_key),
            id:        r.id,
            domain:    r.domain,
            selector:  r.selector,
            algorithm: r.algorithm,
            is_active: r.is_active,
            created_at: r.created_at,
        }
    }
}

#[derive(Deserialize)]
pub struct CreateDkimDto {
    pub domain:    String,
    /// DNS label the key is published under. Defaults to `kubuno`.
    pub selector:  Option<String>,
    /// "rsa-sha256" (default) or "ed25519-sha256".
    pub algorithm: Option<String>,
    /// Sign with this key immediately. Omitted means: yes when the domain has
    /// no signing key yet, no otherwise — because a second key for a domain is
    /// a rotation, and a rotation must not sign before its record is published.
    pub activate:  Option<bool>,
}

/// Only an administrator configures instance-wide signing keys.
fn require_admin(user: &AuthUser) -> Result<(), MailError> {
    if user.role == "admin" {
        Ok(())
    } else {
        Err(MailError::Forbidden)
    }
}

/// A syntactically usable mail domain, lower-cased.
fn normalize_domain(raw: &str) -> Result<String, MailError> {
    let domain = raw.trim().trim_start_matches('@').to_ascii_lowercase();
    if domain.is_empty() || !domain.contains('.') || domain.len() > 253 {
        return Err(MailError::Validation("Domaine invalide".into()));
    }
    if domain.split('.').any(|label| {
        label.is_empty()
            || label.len() > MAX_SELECTOR_LEN
            || !label.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
    }) {
        return Err(MailError::Validation("Domaine invalide".into()));
    }
    Ok(domain)
}

/// The selector becomes a DNS label in `<selector>._domainkey.<domain>`, so it
/// is validated as one: letters, digits and hyphens, no leading or trailing
/// hyphen. Rejecting here rather than at publication time saves the operator a
/// key that can never be published.
fn normalize_selector(raw: Option<&str>) -> Result<String, MailError> {
    let selector = raw.unwrap_or(DEFAULT_SELECTOR).trim().to_ascii_lowercase();
    if selector.is_empty() {
        return Ok(DEFAULT_SELECTOR.to_string());
    }
    let ok = selector.len() <= MAX_SELECTOR_LEN
        && selector.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
        && !selector.starts_with('-')
        && !selector.ends_with('-');
    if !ok {
        return Err(MailError::Validation(
            "Sélecteur invalide : lettres, chiffres et tirets, 63 caractères au plus".into(),
        ));
    }
    Ok(selector)
}

const SELECT_COLUMNS: &str =
    "id, domain, selector, algorithm, public_key, is_active, created_at";

pub async fn list_keys(
    State(state): State<AppState>,
    user: AuthUser,
) -> Result<Json<Vec<DkimKeyView>>, MailError> {
    require_admin(&user)?;
    // Audited: the only interpolation is the `SELECT_COLUMNS` constant above;
    // no caller value reaches the SQL text.
    let rows = sqlx::query_as::<_, DkimKeyRow>(sqlx::AssertSqlSafe(format!(
        "SELECT {SELECT_COLUMNS} FROM mail.dkim_keys_all \
         ORDER BY domain, is_active DESC, created_at DESC"
    )))
    .fetch_all(&state.db)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "list DKIM keys");
        MailError::Database(e)
    })?;
    Ok(Json(rows.into_iter().map(DkimKeyView::from_row).collect()))
}

pub async fn create_key(
    State(state): State<AppState>,
    user: AuthUser,
    Json(dto): Json<CreateDkimDto>,
) -> Result<Json<DkimKeyView>, MailError> {
    require_admin(&user)?;

    let domain   = normalize_domain(&dto.domain)?;
    let selector = normalize_selector(dto.selector.as_deref())?;
    let algorithm = match dto.algorithm.as_deref() {
        Some("ed25519-sha256") => "ed25519-sha256",
        None | Some("rsa-sha256") => "rsa-sha256",
        Some(other) => {
            return Err(MailError::Validation(format!("Algorithme inconnu : {other}")))
        }
    };

    // Generate, then encrypt the private half before it ever touches storage.
    let (private_pem, public_b64) = dkim::generate(algorithm)
        .map_err(|e| MailError::Validation(format!("Génération de clé: {e}")))?;

    let crypto = MailCrypto::new(&state.settings.mail.encryption_key)
        .map_err(|_| MailError::Crypto)?;
    let (enc, nonce) = crypto.encrypt(&private_pem).map_err(|_| MailError::Crypto)?;

    // Insert and (possibly) switch the active key in ONE transaction: the
    // partial unique index allows a single active key per domain, so demoting
    // the previous one and promoting this one cannot be two statements a crash
    // could separate.
    let mut tx = state.db.begin().await.map_err(|e| {
        tracing::error!(error = %e, "create DKIM key: begin");
        MailError::Database(e)
    })?;

    let active_selector: Option<String> = sqlx::query_scalar(
        "SELECT selector FROM mail.dkim_keys_all WHERE domain = $1 AND is_active",
    )
    .bind(&domain)
    .fetch_optional(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "create DKIM key: active lookup");
        MailError::Database(e)
    })?;

    // Default: the first key of a domain signs at once (nothing to break), and
    // so does a key regenerated under the selector that ALREADY signs — the
    // insert below overwrites that row, and leaving it demoted would silently
    // stop signing the domain. Any other new selector is a rotation: it waits
    // for its record to propagate.
    let replaces_active = active_selector.as_deref() == Some(selector.as_str());
    let activate = dto
        .activate
        .unwrap_or(active_selector.is_none() || replaces_active);

    if activate {
        sqlx::query("UPDATE mail.dkim_keys_all SET is_active = FALSE WHERE domain = $1 AND is_active")
            .bind(&domain)
            .execute(&mut *tx)
            .await
            .map_err(|e| {
                tracing::error!(error = %e, "create DKIM key: demote previous");
                MailError::Database(e)
            })?;
    }

    // Audited: `SELECT_COLUMNS` is the sole interpolation; the domain, selector
    // and key material are all bound parameters.
    let row = sqlx::query_as::<_, DkimKeyRow>(sqlx::AssertSqlSafe(format!(
        r#"INSERT INTO mail.dkim_keys_all
             (domain, selector, algorithm, private_key_enc, private_key_nonce, public_key, is_active)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           ON CONFLICT (domain, selector) DO UPDATE
             SET algorithm = EXCLUDED.algorithm,
                 private_key_enc = EXCLUDED.private_key_enc,
                 private_key_nonce = EXCLUDED.private_key_nonce,
                 public_key = EXCLUDED.public_key,
                 is_active = EXCLUDED.is_active,
                 created_at = NOW()
           RETURNING {SELECT_COLUMNS}"#
    )))
    .bind(&domain)
    .bind(&selector)
    .bind(algorithm)
    .bind(&enc)
    .bind(&nonce)
    .bind(&public_b64)
    .bind(activate)
    .fetch_one(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "create DKIM key");
        MailError::Database(e)
    })?;

    tx.commit().await.map_err(|e| {
        tracing::error!(error = %e, "create DKIM key: commit");
        MailError::Database(e)
    })?;

    Ok(Json(DkimKeyView::from_row(row)))
}

/// Switch signing for this key's domain over to this key — the second half of a
/// rotation, once the record has propagated.
pub async fn activate_key(
    State(state): State<AppState>,
    user: AuthUser,
    Path(id): Path<Uuid>,
) -> Result<Json<DkimKeyView>, MailError> {
    require_admin(&user)?;

    let mut tx = state.db.begin().await.map_err(|e| {
        tracing::error!(error = %e, "activate DKIM key: begin");
        MailError::Database(e)
    })?;

    let domain: Option<String> =
        sqlx::query_scalar("SELECT domain FROM mail.dkim_keys_all WHERE id = $1")
            .bind(id)
            .fetch_optional(&mut *tx)
            .await
            .map_err(|e| {
                tracing::error!(error = %e, "activate DKIM key: lookup");
                MailError::Database(e)
            })?;
    let Some(domain) = domain else {
        return Err(MailError::NotFound("Clé DKIM".into()));
    };

    sqlx::query("UPDATE mail.dkim_keys_all SET is_active = FALSE WHERE domain = $1 AND id <> $2")
        .bind(&domain)
        .bind(id)
        .execute(&mut *tx)
        .await
        .map_err(|e| {
            tracing::error!(error = %e, "activate DKIM key: demote others");
            MailError::Database(e)
        })?;

    // Audited: `SELECT_COLUMNS` is the sole interpolation; the id is bound.
    let row = sqlx::query_as::<_, DkimKeyRow>(sqlx::AssertSqlSafe(format!(
        "UPDATE mail.dkim_keys_all SET is_active = TRUE WHERE id = $1 RETURNING {SELECT_COLUMNS}"
    )))
    .bind(id)
    .fetch_one(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "activate DKIM key");
        MailError::Database(e)
    })?;

    tx.commit().await.map_err(|e| {
        tracing::error!(error = %e, "activate DKIM key: commit");
        MailError::Database(e)
    })?;

    Ok(Json(DkimKeyView::from_row(row)))
}

pub async fn delete_key(
    State(state): State<AppState>,
    user: AuthUser,
    Path(id): Path<Uuid>,
) -> Result<Json<serde_json::Value>, MailError> {
    require_admin(&user)?;
    let deleted = sqlx::query("DELETE FROM mail.dkim_keys_all WHERE id = $1")
        .bind(id)
        .execute(&state.db)
        .await
        .map_err(|e| {
            tracing::error!(error = %e, "delete DKIM key");
            MailError::Database(e)
        })?;
    if deleted.rows_affected() == 0 {
        return Err(MailError::NotFound("Clé DKIM".into()));
    }
    Ok(Json(serde_json::json!({ "deleted": true })))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn domain_is_lowercased_and_stripped_of_its_at() {
        assert_eq!(normalize_domain(" @Example.COM ").ok().as_deref(), Some("example.com"));
    }

    #[test]
    fn a_bare_name_is_not_a_mail_domain() {
        assert!(normalize_domain("localhost").is_err());
        assert!(normalize_domain("").is_err());
        assert!(normalize_domain("exa mple.com").is_err());
    }

    #[test]
    fn selector_defaults_and_normalises() {
        assert_eq!(normalize_selector(None).ok().as_deref(), Some("kubuno"));
        assert_eq!(normalize_selector(Some("  ")).ok().as_deref(), Some("kubuno"));
        assert_eq!(normalize_selector(Some(" 2026A ")).ok().as_deref(), Some("2026a"));
    }

    #[test]
    fn selector_must_be_a_publishable_dns_label() {
        assert!(normalize_selector(Some("-lead")).is_err());
        assert!(normalize_selector(Some("trail-")).is_err());
        assert!(normalize_selector(Some("a.b")).is_err());
        assert!(normalize_selector(Some(&"x".repeat(64))).is_err());
    }
}
