import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Copy, KeyRound, Trash2 } from 'lucide-react'
import { Button, ConfirmDialog, Dropdown, Input } from '@ui'
import { useConfirm } from '@kubuno/sdk'
import { mailApi } from '../api'

/**
 * Connecting a mail client to the SMTP/IMAP/POP3 services this instance offers.
 *
 * The password is generated by the server and shown ONCE: it is stored hashed,
 * so there is nothing to display later and nothing to leak from this page. It
 * is deliberately not the Kubuno password — a mail client keeps what it is
 * given for years, and revoking a mailbox credential must not lock the user out
 * of the platform.
 *
 * Whether the services actually run, and on which ports, is the
 * administrator's call in the console (Modules → Mail → ⚙), which is why this
 * page states the fact rather than offering to change it.
 */
export function MailboxAccessTab() {
  const { t } = useTranslation('mail')
  const qc = useQueryClient()
  const [notice, setNotice] = useState<string | null>(null)
  const { confirm, confirmState, handleConfirm, handleCancel } = useConfirm()
  const [address, setAddress] = useState('')
  const [label, setLabel] = useState('')
  const [issued, setIssued] = useState<{ username: string; password: string } | null>(null)

  const { data: accounts } = useQuery({ queryKey: ['mail-accounts'], queryFn: mailApi.listAccounts })
  const { data: credentials = [] } = useQuery({
    queryKey: ['mail-mailbox-credentials'],
    queryFn:  mailApi.listMailboxCredentials,
  })

  const createMut = useMutation({
    mutationFn: () => mailApi.createMailboxCredential({ username: address, label: label || undefined }),
    onSuccess: created => {
      setIssued({ username: created.username, password: created.password })
      setLabel('')
      qc.invalidateQueries({ queryKey: ['mail-mailbox-credentials'] })
    },
    onError: () => setNotice(t('mailbox_create_failed', { defaultValue: 'Création impossible' })),
  })

  const deleteMut = useMutation({
    mutationFn: (id: string) => mailApi.deleteMailboxCredential(id),
    onSuccess:  () => qc.invalidateQueries({ queryKey: ['mail-mailbox-credentials'] }),
  })

  const options = (accounts?.accounts ?? []).map(a => ({ value: a.email_address, label: a.email_address }))

  const copy = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value)
      setNotice(t('copied', { defaultValue: 'Copié' }))
    } catch {
      setNotice(t('copy_failed', { defaultValue: 'Copie impossible' }))
    }
  }

  return (
    <div className="space-y-4 max-w-3xl">
      <section className="p-4 space-y-3 rounded-lg border border-[#e8eaed]">
        <div className="flex items-center gap-2">
          <KeyRound size={16} className="text-text-secondary" />
          <h3 className="text-sm font-bold text-text-primary">
            {t('mailbox_access_title', { defaultValue: 'Accès depuis un client de messagerie' })}
          </h3>
        </div>
        <p className="text-sm text-text-secondary">
          {t('mailbox_access_intro', {
            defaultValue:
              'Créez un mot de passe dédié pour connecter Thunderbird, Outlook ou votre téléphone aux services SMTP, IMAP et POP3 de cette instance. Il ne donne accès qu’à la messagerie et peut être révoqué seul.',
          })}
        </p>

        <div className="flex flex-wrap items-end gap-2">
          <div className="min-w-[240px]">
            <label className="block text-xs text-text-secondary mb-1">
              {t('mailbox_access_address', { defaultValue: 'Adresse' })}
            </label>
            <Dropdown
              options={options}
              value={address}
              onChange={setAddress}
              placeholder={t('mailbox_access_pick', { defaultValue: 'Choisir une adresse' })}
            />
          </div>
          <div className="min-w-[200px]">
            <label className="block text-xs text-text-secondary mb-1">
              {t('mailbox_access_label', { defaultValue: 'Repère (facultatif)' })}
            </label>
            <Input value={label} onChange={e => setLabel(e.target.value)} placeholder="Téléphone, Thunderbird…" />
          </div>
          <Button
            onClick={() => createMut.mutate()}
            disabled={!address || createMut.isPending}
          >
            {t('mailbox_access_create', { defaultValue: 'Générer un mot de passe' })}
          </Button>
        </div>

        {issued && (
          <div className="rounded-lg border border-[#c6dafc] bg-[#e8f0fe] p-3">
            <div className="space-y-2">
              <p className="text-sm">
                {t('mailbox_access_once', {
                  defaultValue:
                    'Notez ce mot de passe maintenant : il n’est pas conservé et ne sera plus affiché.',
                })}
              </p>
              <div className="flex items-center gap-2">
                <code className="px-2 py-1 rounded bg-black/[0.06] text-sm select-all">{issued.password}</code>
                <Button variant="ghost" onClick={() => copy(issued.password)}>
                  <Copy size={14} />
                </Button>
              </div>
              <p className="text-xs text-text-secondary">
                {t('mailbox_access_username', { defaultValue: 'Identifiant' })} : {issued.username}
              </p>
            </div>
          </div>
        )}
      </section>

      <section className="p-4 rounded-lg border border-[#e8eaed]">
        <h3 className="text-sm font-bold text-text-primary mb-2">
          {t('mailbox_access_existing', { defaultValue: 'Mots de passe existants' })}
        </h3>
        {credentials.length === 0 ? (
          <p className="text-sm text-text-secondary">
            {t('mailbox_access_none', { defaultValue: 'Aucun pour l’instant.' })}
          </p>
        ) : (
          <ul className="divide-y divide-[#e8eaed]">
            {credentials.map(c => (
              <li key={c.id} className="flex items-center gap-3 py-2">
                <div className="flex-1 min-w-0">
                  <div className="text-sm text-text-primary truncate">{c.username}</div>
                  <div className="text-xs text-text-secondary">
                    {c.label ? `${c.label} · ` : ''}
                    {c.last_used_at
                      ? t('mailbox_access_last_used', { defaultValue: 'Dernière utilisation' }) +
                        ' ' + new Date(c.last_used_at).toLocaleDateString()
                      : t('mailbox_access_never_used', { defaultValue: 'Jamais utilisé' })}
                  </div>
                </div>
                <Button
                  variant="ghost"
                  onClick={async () => {
                    const ok = await confirm({
                      title:   t('mailbox_access_revoke', { defaultValue: 'Révoquer ce mot de passe ?' }),
                      message: t('mailbox_access_revoke_body', {
                        defaultValue: 'Le client qui l’utilise ne pourra plus relever ce compte.',
                      }),
                    })
                    if (ok) deleteMut.mutate(c.id)
                  }}
                >
                  <Trash2 size={14} />
                </Button>
              </li>
            ))}
          </ul>
        )}
      </section>

      {notice && <p className="text-xs text-text-secondary">{notice}</p>}

      {confirmState && (
        <ConfirmDialog {...confirmState} onConfirm={handleConfirm} onCancel={handleCancel} />
      )}
    </div>
  )
}
